.TH "SkiaSharp.Unity.SkottieMarkers" 3 "SkiaForUnity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkiaSharp.Unity.SkottieMarkers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstate\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstate\fP \fBGetStateByName\fP (string name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "List< \fBstate\fP > \fBmarkers\fP = new List<\fBstate\fP>()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBmarkers\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBstate\fP SkiaSharp\&.Unity\&.SkottieMarkers\&.GetStateByName (string name)"

.PP
Definition at line \fB12\fP of file \fBmarkers\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "List<\fBstate\fP> SkiaSharp\&.Unity\&.SkottieMarkers\&.markers = new List<\fBstate\fP>()"

.PP
Definition at line \fB5\fP of file \fBmarkers\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SkiaForUnity from the source code\&.
