.TH "SkiaSharp.Unity" 3 "SkiaForUnity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkiaSharp.Unity
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSkottieMarkers\fP"
.br
.ti -1c
.RI "class \fBSkottiePlayer\fP"
.br
.RI "Provides functionality to play and control Lottie animations in Unity\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SkiaForUnity from the source code\&.
