.TH "SkiaSharp.Unity.SkottieMarkers.state" 3 "SkiaForUnity" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SkiaSharp.Unity.SkottieMarkers.state
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtm\fP"
.br
.ti -1c
.RI "int \fBdr\fP"
.br
.ti -1c
.RI "string \fBcm\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBmarkers\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "string SkiaSharp\&.Unity\&.SkottieMarkers\&.state\&.cm"

.PP
Definition at line \fB9\fP of file \fBmarkers\&.cs\fP\&.
.SS "int SkiaSharp\&.Unity\&.SkottieMarkers\&.state\&.dr"

.PP
Definition at line \fB8\fP of file \fBmarkers\&.cs\fP\&.
.SS "int SkiaSharp\&.Unity\&.SkottieMarkers\&.state\&.tm"

.PP
Definition at line \fB7\fP of file \fBmarkers\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SkiaForUnity from the source code\&.
